name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Har kuni yaratiladi
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: miraziz-Developer
          outputs: dist/snake.svg

      - name: Push the generated snake
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg
